### PR TITLE
Synchronize access to WordNet lemmatizer

### PR DESCRIPTION
**Pull request by alvaromorales**

### CODE REVIEW

**Comment by moldot** [comment]
Was race condition a problem without the lock?

**Comment by alvaromorales** [comment]
Yeah, I got the `Attribute not found: LazyLoader` exception. This seems to be an nltk-specific thing. Can you investigate? I'm not sure that locking fixes the problem.

**Comment by moldot** [comment]
Per the stacktrace in #82 the problem seems to be in `wordtypes.py` (`is_person`) and not the lemmatizer. Have you seen a lazyloader problem from the lemmatizer? (The stacktrace should contain a line from `deftree.py`.)

**Comment by alvaromorales** [comment]
Yes, I saw a stacktrace from the lemmatizer pointing to deftree.py. After locking access to `lmtzr`, this error trace is gone -- I think the problem has gone away.

(Race conditions make me sad.)

**Comment by moldot** [comment]
Hmm interesting that #82 is not working.

**Comment by moldot** [comment]
Made a global lock. Hope this helps..

**Comment by alvaromorales** [comment]
I think #82 is a good-enough solution to this problem. I see no improvement with a global lock, in the last few set of runs.

**Pull request closed without merging**
