### PR TITLE
Lemmatization

### LINKED ISSUE #38: Lemmatization
Only use lemmatizer on nouns. Lemmatizing other POS sometimes change the meaning or POS of the words. For example "localized" --> "localize". For non-noun, only lower case, and remove 'the' in NEs.

### PR DESCRIPTION
**Pull request by moldot**
Turn the lemma_ field in HeadModifierTree into get_lemma function, which takes a list of POS tags of words that should be lemmatized. 

Query functions can pass this pos tag list to control what types of words are to be lemmatized.

Fixed #38.

Unittest coming in the future

### CODE REVIEW

**Comment by alvaromorales** [comment]
I think it would be nice to put lemmatization under a flag. Callers can then specify if they want lemmas or original tokens.

**Comment by moldot** [comment]
Edited as recommended.

**Comment by alvaromorales** [comment]
lgtm :airplane:

**Comment by sfelshin** [comment]
On Jan 13, 2016, at 10:46 AM, moldot <notifications@github.com> wrote:
> For non-nouns, only lower case.

I'm not sure how you mean this, but in case it's relevant, I note that it is possible to have uppercase letters in verbs and adjectives, such as adjectives of geographic location ("African"), adjectives derived from proper names ("Cartesian"), verbs formed from geographic locations ("Americanize"), etc.

**Comment by moldot** [comment]
That I meant to lower all words regardless of the POS tags. So, African -> african, Americanize -> americanize. Specifically for nouns, by default, we actually lemmatize them, so Americans will become american. You can, however, require by using lemma_pos flag that other words be lemmatized, too.

**Pull request merged**
