### PR TITLE
Add end-to-end tests for assertion definition

### PR DESCRIPTION
**Pull request by moldot**
Add a number of end-to-end tests for assertions. Most tests use
sentence from wikipedia. Each test is commented with what it is testing.

### CODE REVIEW

**Comment by alvaromorales** [comment]
I see you ported the method names from whoami (I defined many of them). These method names are actually bad practice, because they don't help us understand what the test checks. I take the blame for this -- but we can use this as an opportunity to make the code better.

Examples: `test_complex_compound` is much more informative than `test_is_a_law_case`. `test_unicode` is better than `test_is_a_municipality`.

Try to group tests logically. I think multiple asserts in one `test_` method are fine as long as they test the same 'unit' of functionality.

**Comment by alvaromorales** [comment]
* No need to add error messages
* Look at argument order in https://docs.python.org/2/library/unittest.html (e.g. `assertItemsEqual(actual, expected)`

**Comment by moldot** [comment]
Interestingly, this is the docstring of assertItemsEquals:
 {{

Help on method assertItemsEqual in module unittest.case:

assertItemsEqual(self, expected_seq, actual_seq, msg=None) unbound unittest.case.TestCase method
    An unordered sequence specific comparison. It asserts that
    actual_seq and expected_seq have the same element counts.
    Equivalent to::

        self.assertEqual(Counter(iter(actual_seq)),
                         Counter(iter(expected_seq)))

    Asserts that each element has the same count in both sequences.
    Example:
        - [0, 1, 1] and [1, 0, 1] compare equal.
        - [0, 0, 1] and [0, 1] compare unequal.
}}

**Comment by moldot** [comment]
Interestingly, here's the docstring from unittest.TestCase.assertItemsEqual

```
assertItemsEqual(self, expected_seq, actual_seq, msg=None) unbound unittest.case.TestCase method
    An unordered sequence specific comparison. It asserts that
    actual_seq and expected_seq have the same element counts.
    Equivalent to::

        self.assertEqual(Counter(iter(actual_seq)),
                         Counter(iter(expected_seq)))

    Asserts that each element has the same count in both sequences.
    Example:
        - [0, 1, 1] and [1, 0, 1] compare equal.
        - [0, 0, 1] and [0, 1] compare unequal.
```

I don't think the order actually matters. In the error message, they just call them 'first' and 'second' list. Anyhow, I'll stick with the variable names in the docstring.

**Comment by alvaromorales** [comment]
lgtm! :rocket: :ship: :airplane:

**Comment by moldot** [comment]
Closed #41

**Pull request merged**
